### ISSUE TITLE
Just border, not radius

### ISSUE THREAD

**Issue by antonioreyna** [KogiMobileSAS/RoundedViews#2]
Is it possible to not use the radiusmultiplayer and just set the border? i tried not setting it but the result is a weird shape?

thanks.

**Comment by juanuribeo13** [comment]
Hey @antonioreyna, yes it is possible to just set the border, you might be getting the weird shape because you set some value for the `radiusMultiplier`, if that's the case you can delete that value from the interface builder or don't set any by code and it'll be fixed.

I noticed that we are using `1` as the default value for `radiusMultiplier` but if you set that value then you'll get the weird shape. I'll update the code and make a new release using `0` as the default value since that's the default value for the `cornerRadius`.

Another solution is to use any negative number, then the view's layer will ignore the `cornerRadius`. In the current version using `0` won't work because there will be a division by `0` and the view disappears.

I hope that fixes your problem.

**Comment by juanuribeo13** [comment]
I just uploaded version 1.0.2, now you can also disable the `radiusMultiplier` by setting it to `0`

**Comment by antonioreyna** [comment]
great! thank you so much!
