### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by antonioreyna** [KogiMobileSAS/RoundedViews#3]
Hello,

On a new project, i am using this library via Carthage, but apparently when you use carthage there is no possibility to make the interface builder show the designable variables.

Some people propose subclassing the library classes but on this one i think is not possible to override the cornerRadius and border attributes.

Reference: [here](http://stackoverflow.com/questions/29933691/ibdesignable-from-external-framework/37631860#37631860)

What do you think? could it be possible to make something similar to use it with Carthage instead of cocoapods?

Thanks for this awesome project!

**Comment by juanuribeo13** [comment]
Hey, it looks like that's a limitation that frameworks have, you can check the [issue](https://github.com/Carthage/Carthage/issues/335) on Carthage.

Maybe subclassing will work, I tried this and there's no compiler errors, but I didn't test if that actually works.

``` swift
@IBDesignable class RoundedView: RoundedViews.RoundedView {
    @IBInspectable override var radiusMultiplier: CGFloat {
        get {
            return super.radiusMultiplier
        }
        set {
            super.radiusMultiplier = newValue
        }
    }

    @IBInspectable override var borderWidth: CGFloat {
        get {
            return super.borderWidth
        }
        set {
            super.borderWidth = newValue
        }
    }

    @IBInspectable override var borderColor: UIColor? {
        get {
            return super.borderColor
        }
        set {
            super.borderColor = newValue
        }
    }
}
```

The thing is that you'll have to do that for every view you'll use on your project (RoundedView, RoundedButton, RoundedImage, etc). Another thing you can try is to set the `radiusMultiplier` and the other properties using [User Defined Runtime Attributes](https://developer.apple.com/library/mac/recipes/xcode_help-interface_builder/Chapters/AddUserDefinedRuntimeAttributes.html) but keep in mind that using it that way you won't see the final result in interface builder.

I'm going to close this since it looks like there's nothing we can do from our side, if you find out about something that can be done feel free to open it again.

I'm glad you like the project.
